### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: xyz/upperlevel/spigot/book/BookUtil

### ISSUE THREAD

**Issue by Two-Zero-M** [upperlevel/book-api#11]
[22:59:32] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Arun_RPG v1.0.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2277) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NoClassDefFoundError: xyz/upperlevel/spigot/book/BookUtil
	at com.codns.arun.quste.onInventoryClick(quste.java:97) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	... 18 more
Caused by: java.lang.ClassNotFoundException: xyz.upperlevel.spigot.book.BookUtil
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at com.codns.arun.quste.onInventoryClick(quste.java:97) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	... 18 more

dissolvent please

**Comment by LiamDev06** [comment]
Yes please answer this! I also need help with this. Something is wrong and not working

**Comment by SnowyCoder** [comment]
This does not seem like a library error: `Caused by: java.lang.ClassNotFoundException: xyz.upperlevel.spigot.book.BookUtil`, did you forget to include the library in your plugin jar?

**Comment by LiamDev06** [comment]
No I don't think I did at least?

**Comment by SnowyCoder** [comment]
Check if your jar contains the file `xyz/upperlevel/spigot/book/BookUtil.class`, if it does then we have a big problem since the JVM doesn't seem to find it.
If you want an example of what a final JAR should look like you can find it here: https://repo1.maven.org/maven2/xyz/upperlevel/spigot/book/spigot-book-api/1.4/spigot-book-api-1.4-example.jar (note that a real plugin JAR should also have the library relocated so it does not conflict with other library versions from other plugins)

**Comment by SnowyCoder** [comment]
I'm, closing this issue since it's been stale for a month now
