### ISSUE TITLE
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.save(net.minecraft.nbt.NBTTagCompound) (1.18-pre8)

### ISSUE THREAD

**Issue by quiquelhappy** [upperlevel/book-api#27]
I'm getting the following stacktrace when using the library on 1.18-pre8:

```
[07:24:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'waypointregistry:waypoint' in plugin WaypointRegistry v1.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.18-pre8-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18-pre8-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:800) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1937) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1776) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1757) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1157) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1136) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1129) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1113) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1037) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-pre8-R0.1-SNAPSHOT.jar:3312-Spigot-7840c2a-5a39a23]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at xyz.upperlevel.spigot.book.BookUtil$BookBuilder.pages(BookUtil.java:153) ~[?:?]
        at co.purevanilla.mcplugins.WaypointRegistry.util.BookGeneration.getWaypointBook(BookGeneration.java:73) ~[?:?]
        at co.purevanilla.mcplugins.WaypointRegistry.cmd.WaypointCMD.onCommand(WaypointCMD.java:106) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.18-pre8-R0.1-SNAPSHOT.jar:?]
        ... 21 more
Caused by: java.lang.IllegalStateException: Cannot initiate reflections for v1_18_R1
        at xyz.upperlevel.spigot.book.NmsBookHelper.<clinit>(NmsBookHelper.java:123) ~[?:?]
        at xyz.upperlevel.spigot.book.BookUtil$BookBuilder.pages(BookUtil.java:153) ~[?:?]
        at co.purevanilla.mcplugins.WaypointRegistry.util.BookGeneration.getWaypointBook(BookGeneration.java:73) ~[?:?]
        at co.purevanilla.mcplugins.WaypointRegistry.cmd.WaypointCMD.onCommand(WaypointCMD.java:106) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.18-pre8-R0.1-SNAPSHOT.jar:?]
        ... 21 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.save(net.minecraft.nbt.NBTTagCompound)
        at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
        at xyz.upperlevel.spigot.book.NmsBookHelper.<clinit>(NmsBookHelper.java:120) ~[?:?]
        at xyz.upperlevel.spigot.book.BookUtil$BookBuilder.pages(BookUtil.java:153) ~[?:?]
        at co.purevanilla.mcplugins.WaypointRegistry.util.BookGeneration.getWaypointBook(BookGeneration.java:73) ~[?:?]
        at co.purevanilla.mcplugins.WaypointRegistry.cmd.WaypointCMD.onCommand(WaypointCMD.java:106) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.18-pre8-R0.1-SNAPSHOT.jar:?]
        ... 21 more
```

I'm not 100% sure if this is being caused by book-api or spigot, (I find weird ``net.minecraft.world.item.ItemStack.save(net.minecraft.nbt.NBTTagCompound)`` isn't a method on this release, but it was on previous. Maybe it was deprecated?

**Comment by MiniDigger** [comment]
momap:
![https://i.imgur.com/RnTdyYt.png](https://i.imgur.com/RnTdyYt.png)
obfuscated back to spigot mappings by paper:
![https://i.imgur.com/yjkf98d.png](https://i.imgur.com/yjkf98d.png)

**Comment by SnowyCoder** [comment]
But why did they drop the de-obfuscation? 
Anyways, sorry for the delay, today I'll try to fix it, thank you!

**Comment by MiniDigger** [comment]
JustSpigotThings?

**Comment by SnowyCoder** [comment]
I have bad news and good news.
Seems like ["only classes remain 'Spigot Mapped'"](https://www.spigotmc.org/threads/9-years-of-spigotmc-spigot-bungeecord-1-18-rc3.534760/) so there's no chance that we'll get the NMS code working again without re-checking every mapping.
On the other side someone added all of the APIs that I need ([this](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/BookMeta.Spigot.html#setPages(net.md_5.bungee.api.chat.BaseComponent%5B%5D...)) and [this](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#openBook(org.bukkit.inventory.ItemStack))) to spigot some versions ago, so I can make this tiny project NMS-free and compatible forever, I'll just need a bit of tinkering to keep retro-compatibility while leaving the source code clean.

**Comment by SnowyCoder** [comment]
Yes, more bad news, we require NMS for ItemStack to JSON conversion (used if the dev. needs to show an item on hover).
Since I don't want to drop this (as it seems like this is the only project that supports itemstacks on hover) I divided the NMS into two, the heavier legacy openBook/setPages code (used only if the newer lightweight one is not supported) and another class that has just ItemStack saving. Everything is loaded on-demand so the average user that does not need ItemStacks on hover will not even load any NMS-reflection code.

This works perfectly so I'll push the new release shortly, thank you both for the report and for the help!

**Comment by quiquelhappy** [comment]
is there a way to open the book to the player now being on the safe side for future updates?
edit: aslo, thanks for the update

**Comment by SnowyCoder** [comment]
What do you mean on the safe side?
It should not break again for a long time since it now uses official Spigot APIs.
I only use some unofficial API if you put an ItemStack on hover, and that's the only fragile part of the library.

**Comment by quiquelhappy** [comment]
sorry, I was testing using the wrong version, don't know how I could have missed that. Thanks!

**Comment by SnowyCoder** [comment]
No problem!
Tell me if you need help on anything :+1:
