### ISSUE TITLE
Cant open book with BookUtil.openPlayer

### ISSUE THREAD

**Issue by florianokaplo** [upperlevel/book-api#28]
Error Code:
`[05.12 15:25:25.091] INFO: [Lobby-1] org.bukkit.command.CommandException: Unhandled exception executing command 'rules' in plugin DexCube-Base v1.0.0
[05.12 15:25:25.091] INFO: [Lobby-1]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:790) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.server.TickTask.run(SourceFile:18) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at java.lang.Thread.run(Thread.java:833) [?:?]
[05.12 15:25:25.091] INFO: [Lobby-1] Caused by: java.lang.IllegalArgumentException: Book must be Material.WRITTEN_BOOK
[05.12 15:25:25.091] INFO: [Lobby-1]    at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.openBook(CraftPlayer.java:1738) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    at xyz.upperlevel.spigot.book.internals.SpigotBookHelper.openBook(SpigotBookHelper.java:21) ~[?:?]
[05.12 15:25:25.091] INFO: [Lobby-1]    at xyz.upperlevel.spigot.book.BookUtil.openPlayer(BookUtil.java:67) ~[?:?]
[05.12 15:25:25.091] INFO: [Lobby-1]    at at.florianokaplo.survival.commands.CMD_regeln.onCommand(CMD_regeln.java:128) ~[?:?]
[05.12 15:25:25.091] INFO: [Lobby-1]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper.jar:3284-Spigot-3892929-0ebef35]
[05.12 15:25:25.091] INFO: [Lobby-1]    ... 19 more
`

Sourcecode:
`ItemStack book1 = BookUtil.writtenBook()
                        .author("Server Administrator")
                        .title("Minecraft-Server Regeln")
                        .pages(
                                new BookUtil.PageBuilder().add("Test").build()
                        ).build();

                BookUtil.openPlayer(p, book1);`

**Comment by SnowyCoder** [comment]
Hi, sorry for the delay, are you using `api-version: 1.13` in your `plugin.yml`?
Long explaination: For what I can see for old plugins spigot/paper uses different Material variants and that messes up their code quite a bit.

**Comment by florianokaplo** [comment]
Hat den fehler behoben. Danke! :)
