### ISSUE TITLE
Error when using 1.18.2.

### ISSUE THREAD

**Issue by BingYanchi** [upperlevel/book-api#31]
Plugin:
```java
package cn.yistars.URLBook.book;

import cn.yistars.URLBook.manager.ConfigManager;
import net.md_5.bungee.api.chat.TextComponent;
import org.bukkit.ChatColor;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import xyz.upperlevel.spigot.book.BookUtil;

public class BookGUI {
    public static void URLBook(Player player, String URL) {
        ItemStack book = BookUtil.writtenBook()
            .author("Bing")
            .title("URLBook")
            .pages(
                new BookUtil.PageBuilder()
                    .add(new TextComponent(ConfigManager.bookLang.get("URLBookTitle")))
                    .newLine().newLine()
                    .add(new TextComponent(ConfigManager.bookLang.get("URLBook")))
                    .newLine().newLine()

                    .add(BookUtil.TextBuilder.of(URL)
                        .style(ChatColor.BOLD)
                        .color(ChatColor.GREEN)
                        .build()
                    )
                    .newLine().newLine()
                    .add(BookUtil.TextBuilder.of(ConfigManager.bookLang.get("URLBookButton"))
                        .color(ChatColor.GOLD)
                        .style(ChatColor.BOLD)
                        .onClick(BookUtil.ClickAction.openUrl(URL))
                        .onHover(BookUtil.HoverAction.showText(ConfigManager.bookLang.get("URLBookButtonHover")))
                        .build()
                    )
                    .build()
            )
            .build();
        BookUtil.openPlayer(player, book);
    }
}

```

Server Log
```
[17:06:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bingurlbook' in plugin BingURLBook v1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at cn.yistars.book.BookUtil$BookBuilder.pages(BookUtil.java:143) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at cn.yistars.URLBook.book.BookGUI.URLBook(BookGUI.java:15) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at cn.yistars.URLBook.command.URLBookCommand.onCommand(URLBookCommand.java:35) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more
Caused by: java.lang.IllegalStateException: Cannot initiate reflections for v1_18_R2
        at cn.yistars.book.NmsBookHelper.<clinit>(NmsBookHelper.java:123) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at cn.yistars.book.BookUtil$BookBuilder.pages(BookUtil.java:143) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at cn.yistars.URLBook.book.BookGUI.URLBook(BookGUI.java:15) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at cn.yistars.URLBook.command.URLBookCommand.onCommand(URLBookCommand.java:35) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.save(net.minecraft.nbt.NBTTagCompound)
        at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
        at cn.yistars.book.NmsBookHelper.<clinit>(NmsBookHelper.java:120) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at cn.yistars.book.BookUtil$BookBuilder.pages(BookUtil.java:143) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at cn.yistars.URLBook.book.BookGUI.URLBook(BookGUI.java:15) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at cn.yistars.URLBook.command.URLBookCommand.onCommand(URLBookCommand.java:35) ~[BingURLBook-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more
```

**Comment by SnowyCoder** [comment]
Hello!
Please check that you're using the latest version and always include the used plugin's version when reporting an issue.
From the logs I think that you're using v1.5, am I correct?
Can you check if v1.6 works?
