### ISSUE TITLE
Not working on 1.8.9

### ISSUE THREAD

**Issue by Xayanix** [upperlevel/book-api#6]
PaperSpigot 1.8.9
```
[04:00:43] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.EnumHand
[04:00:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[04:00:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[04:00:43] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[04:00:43] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[04:00:43] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[04:00:43] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[04:00:43] [Server thread/WARN]: 	at xyz.upperlevel.spigot.book.NmsBookHelper.getNmsClass(NmsBookHelper.java:225)
[04:00:43] [Server thread/WARN]: 	at xyz.upperlevel.spigot.book.NmsBookHelper.<clinit>(NmsBookHelper.java:62)
[04:00:43] [Server thread/WARN]: 	at xyz.upperlevel.spigot.book.BookUtil$BookBuilder.pages(BookUtil.java:121)
[04:00:43] [Server thread/WARN]: 	at net.xayanix.nssv.core.manager.IGShopManager.createBook(IGShopManager.java:159)
[04:00:43] [Server thread/WARN]: 	at net.xayanix.nssv.core.manager.IGShopManager.init(IGShopManager.java:42)
[04:00:43] [Server thread/WARN]: 	at net.xayanix.nssv.core.basic.Main.onEnable(Main.java:106)
[04:00:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[04:00:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[04:00:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[04:00:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[04:00:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[04:00:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[04:00:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[04:00:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[04:00:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[04:00:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[04:00:43] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[04:00:43] [Server thread/ERROR]: Error occurred while enabling xxx (Is it up to date?)
java.lang.ExceptionInInitializerError
	at xyz.upperlevel.spigot.book.BookUtil$BookBuilder.pages(BookUtil.java:121) ~[?:?]
	at net.xayanix.nssv.core.manager.IGShopManager.createBook(IGShopManager.java:159) ~[?:?]
	at net.xayanix.nssv.core.manager.IGShopManager.init(IGShopManager.java:42) ~[?:?]
	at net.xayanix.nssv.core.basic.Main.onEnable(Main.java:106) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [ChestPvP.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalStateException: Cannot initiate reflections for v1_8_R3
	at xyz.upperlevel.spigot.book.NmsBookHelper.<clinit>(NmsBookHelper.java:82) ~[?:?]
	... 15 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.EntityPlayer.a(net.minecraft.server.v1_8_R3.ItemStack, null)
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_171]
	at xyz.upperlevel.spigot.book.NmsBookHelper.<clinit>(NmsBookHelper.java:63) ~[?:?]
	... 15 more```

**Comment by SnowyCoder** [comment]
Ok, I think I found the bug: the double hands were added in MC 1.8.9 but spigot didn't have that release so I tought they were added in MC 1.9,
Still where did you find the 1.8.9 release? I can't find it online
