### ISSUE TITLE
Does not work on 1.16.3

### ISSUE THREAD

**Issue by ignissak** [upperlevel/book-api#8]
```
[16:47:39 ERROR]: Could not pass event PlayerJoinEvent to DeadByDaylight v1.0.0
java.lang.ExceptionInInitializerError: null
        at xyz.upperlevel.spigot.book.BookUtil$BookBuilder.pages(BookUtil.java:136) ~[?:?]
        at net.ignissak.deadbydaylight.game.interfaces.GamePlayer.giveBook(GamePlayer.kt:68) ~[?:?]
        at net.ignissak.deadbydaylight.game.interfaces.GamePlayer.onJoin(GamePlayer.kt:59) ~[?:?]
        at net.ignissak.deadbydaylight.game.PlayerManager.registerPlayer(PlayerManager.kt:43) ~[?:?]
        at net.ignissak.deadbydaylight.event.JoinListener.onJoin(JoinListener.kt:35) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor273.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-216]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-216]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-216]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-216]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.IllegalStateException: Cannot initiate reflections for v1_16_R2
        at xyz.upperlevel.spigot.book.NmsBookHelper.<clinit>(NmsBookHelper.java:104) ~[?:?]
        ... 21 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R2.EntityPlayer.a(net.minecraft.server.v1_16_R2.ItemStack, net.minecraft.server.v1_16_R2.EnumHand)
        at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_262]
        at xyz.upperlevel.spigot.book.NmsBookHelper.<clinit>(NmsBookHelper.java:81) ~[?:?]
        ... 21 more
```
My code:
```
val book = BookUtil.writtenBook()
                .author("CraftMania")
                .title("§9Manuál §7(klikni pravym)")
                .pages(
                        // First page
                        BookUtil.PageBuilder()
                                .add(
                                        BookUtil.TextBuilder.of("Základní informace")
                                                .color(ChatColor.GOLD)
                                                .style(ChatColor.BOLD)
                                                .build()
                                )
                                .newLine()
                                .newLine()
                                .add("Tato hra je 1 versus 4, kde killer se snaží zabít survivory a survivoři se snaží z mapy utéct. Pro více informácií k rolím přejdi na další stránky.")
                                .build(),
                        // Second page
                        BookUtil.PageBuilder()
                                .add(
                                        BookUtil.TextBuilder.of("Hrání za killera")
                                                .color(ChatColor.RED)
                                                .style(ChatColor.BOLD)
                                                .build()
                                )
                                .newLine()
                                .newLine()
                                .add("Jako killer musíš zabít všechny survivory. Survivory mají maximálně 2 životy, které si můžou doplnit bándáži. Tvoje sekera dáva 2 damage (1 srdíčko). Hráč neumře ihned ale leží na zemi po dobu 20 sekund, kdy ho můžou ostatní oživit. Také můžeš přitáhnout survivory k sobě pomocí hooku. Obidve tvoje zbraně mají cooldown po použití a po zasažení survivora sekerou mají speed boost.")
                                .build(),
                        // Third page
                        BookUtil.PageBuilder()
                                .add(
                                        BookUtil.TextBuilder.of("Hrání za survivora")
                                                .color(ChatColor.GREEN)
                                                .style(ChatColor.BOLD)
                                                .build()
                                )
                                .newLine()
                                .newLine()
                                .add("Jako survivor musíš spolu s ostatníma opravit aspoň 5 generátorů a utéct cez jednu z 2 brán na mapě. Baterie do generátorů jsou schované v truhlách nebo se spawnují po zemi. V těchto truhlách můžeš získat bandáž na vyléčení a zapalovač, aby jsi mohl vidět lépe, protože budeš mít blindness. Pokud nějaký spoluhráč bude zraněn tak dostaneš kompas, který tě k nemu naviguje a můžeš ho oživit shiftovaním pri něm.")
                                .build(),
                        // Fourth page
                        BookUtil.PageBuilder()
                                .add(
                                        BookUtil.TextBuilder.of("Pravidla")
                                                .color(ChatColor.RED)
                                                .style(ChatColor.BOLD)
                                                .build()
                                )
                                .newLine()
                                .newLine()
                                .add("1. Nepodváděj a nevyužívej bugy, raději je nahlaš a dostaneš za odmenu.")
                                .newLine()
                                .add("2. Nepoužívej cheaty, kazíš hru sobě i ostatním.")
                                .newLine()
                                .add("3. Nenádavej v chatu.")
                                .newLine()
                                .add("Platí tady všechny pravidla CraftManie.")
                                .build()
                )
                .build()
        player.inventory.setItem(1, book)
```

**Comment by ignissak** [comment]
Looks like I was using 1.2 instead of 1.3. My bad 😄
